version: "2.3"
services:
  frontend:
    container_name: angular_frontend
    build: .
    restart: always
    ports:
      - "4200:80"
    networks:
      - todo_frontend

networks:
    todo_frontend: